import { ArrowRight, BookOpen, CalendarDays, FileText, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '../common/Badge'
import { Button } from '../common/Button'
import { Card, CardContent, CardHeader, CardTitle } from '../common/Card'
import { mockConferences } from '../../data/conferences'
import type { AbstractStatus } from '../../types/abstract'
import type { RegistrationStatus } from '../../types/registration'
const statusVariant = (status: AbstractStatus | RegistrationStatus) => status === 'APPROVED' || status === 'CONFIRMED' ? 'success' : status === 'REJECTED' || status === 'CANCELLED' ? 'error' : status === 'REVISION_REQUIRED' ? 'warning' : 'info'
const label = (value: string) => value.replaceAll('_', ' ').replace(/\b\w/g, (letter) => letter.toUpperCase())
export function UserStatCard({ title, value, icon: Icon }: { title: string; value: number; icon: typeof CalendarDays }) { return <Card className="az-user-stat"><CardContent><Icon size={23} /><div><p>{title}</p><strong>{value}</strong></div></CardContent></Card> }
export function UpcomingConferences({ conferenceIds }: { conferenceIds: string[] }) { const conferences = mockConferences.filter((conference) => conferenceIds.includes(conference.id)).slice(0, 3); return <Card><CardHeader><CardTitle>Upcoming conferences</CardTitle></CardHeader><CardContent className="az-user-list">{conferences.map((conference) => <article key={conference.id} className="az-user-conference"><div><h3>{conference.title}</h3><p>{conference.startDate} · {conference.city}, {conference.country}</p><Badge variant="success">Registered</Badge></div><Link className="az-button az-button--outline az-button--sm" to={`/conferences/${conference.slug}`}>View Conference</Link></article>)}</CardContent></Card> }
export function RecentRegistrations({ items }: { items: { id: string; conferenceId: string; registrationType: string; registeredAt: string; status: RegistrationStatus }[] }) { return <Card><CardHeader><CardTitle>Recent registrations</CardTitle></CardHeader><CardContent><div className="az-user-table"><div className="az-user-table__head"><span>Conference</span><span>Type</span><span>Date</span><span>Status</span></div>{items.map((item) => <div className="az-user-table__row" key={item.id}><span>{mockConferences.find((conference) => conference.id === item.conferenceId)?.title}</span><span>{item.registrationType}</span><span>{item.registeredAt}</span><Badge variant={statusVariant(item.status)}>{label(item.status)}</Badge></div>)}</div></CardContent></Card> }
export function RecentAbstracts({ items }: { items: { id: string; conferenceId: string; title: string; submittedAt: string; status: AbstractStatus }[] }) { return <Card><CardHeader><CardTitle>Recent abstracts</CardTitle></CardHeader><CardContent><div className="az-user-table"><div className="az-user-table__head"><span>Title</span><span>Conference</span><span>Submitted</span><span>Status</span></div>{items.map((item) => <div className="az-user-table__row" key={item.id}><Link to={`/dashboard/abstracts/${item.id}`}>{item.title}</Link><span>{mockConferences.find((conference) => conference.id === item.conferenceId)?.title}</span><span>{item.submittedAt}</span><Badge variant={statusVariant(item.status)}>{label(item.status)}</Badge></div>)}</div></CardContent></Card> }
export function QuickActions() { return <Card><CardHeader><CardTitle>Quick actions</CardTitle></CardHeader><CardContent className="az-quick-actions"><Link to="/conferences"><Button variant="outline"><BookOpen size={17} />Browse Conferences</Button></Link><Link to="/dashboard/abstracts/new"><Button variant="outline"><FileText size={17} />Submit Abstract</Button></Link><Link to="/dashboard/registrations"><Button variant="outline"><ArrowRight size={17} />View Registrations</Button></Link><Link to="/dashboard/profile"><Button variant="outline"><UserRound size={17} />Update Profile</Button></Link></CardContent></Card> }
