export const ROUTES = {
  home: '/',
  about: '/about',
  conferences: '/conferences',
  conferenceDetails: '/conferences/:slug',
  speakers: '/speakers',
  speakerDetails: '/speakers/:slug',
  contact: '/contact',
  faq: '/faq',
  gallery: '/gallery',
  blogs: '/blogs',
  blogDetails: '/blogs/:slug',
  privacyPolicy: '/privacy-policy',
  terms: '/terms',
  sitemap: '/sitemap',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  adminLogin: '/admin/login',
  userDashboard: '/dashboard',
  adminDashboard: '/admin/dashboard',
} as const;
