import { useState, type FormEvent } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '../../components/common/Button'
import { Input } from '../../components/common/Input'
import { Textarea } from '../../components/common/Textarea'
import { defaultUserProfile } from '../../data/userProfile'
import { useAuth } from '../../hooks/useAuth'
const key = (id: string) => `aztech.profile.${id}`
export default function EditProfile() { const { user } = useAuth(); const navigate = useNavigate(); const stored = localStorage.getItem(key(user?.id ?? '')); const [form, setForm] = useState(stored ? JSON.parse(stored) as typeof defaultUserProfile : { ...defaultUserProfile, id: user?.id ?? defaultUserProfile.id, name: user?.name ?? defaultUserProfile.name, email: user?.email ?? defaultUserProfile.email }); const [message, setMessage] = useState(''); const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value })); const submit = (e: FormEvent) => { e.preventDefault(); if (form.name.trim().length < 2) return setMessage('Full name must contain at least 2 characters.'); if ((form.linkedin && !URL.canParse(form.linkedin)) || (form.website && !URL.canParse(form.website))) return setMessage('Please enter valid URLs.'); localStorage.setItem(key(form.id), JSON.stringify(form)); navigate('/dashboard/profile') }; return <><section className="az-user-page__intro"><p className="az-auth__eyebrow">My Profile</p><h2>Edit Profile</h2></section><form className="az-user-form" onSubmit={submit}><Input label="Full Name" required value={form.name} onChange={(e) => update('name', e.target.value)} /><Input label="Email" value={form.email} readOnly /><Input label="Phone" value={form.phone ?? ''} onChange={(e) => update('phone', e.target.value)} /><Input label="Organization" value={form.organization ?? ''} onChange={(e) => update('organization', e.target.value)} /><Input label="Job Title" value={form.jobTitle ?? ''} onChange={(e) => update('jobTitle', e.target.value)} /><Input label="Country" value={form.country ?? ''} onChange={(e) => update('country', e.target.value)} /><Input label="City" value={form.city ?? ''} onChange={(e) => update('city', e.target.value)} /><Textarea label="Biography" maxLength={500} value={form.biography ?? ''} onChange={(e) => update('biography', e.target.value)} /><Input label="Areas of Interest" helperText="Separate interests with commas." value={Array.isArray(form.interests) ? form.interests.join(', ') : form.interests ?? ''} onChange={(e) => update('interests', e.target.value)} /><Input label="LinkedIn" type="url" value={form.linkedin ?? ''} onChange={(e) => update('linkedin', e.target.value)} /><Input label="Website" type="url" value={form.website ?? ''} onChange={(e) => update('website', e.target.value)} />{message && <p className="az-auth-error" role="alert">{message}</p>}<div className="az-user-form__actions"><Button type="button" variant="ghost" onClick={() => navigate('/dashboard/profile')}>Cancel</Button><Button type="submit">Save Changes</Button></div></form></> }
