import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Button } from '../common/Button'
import { Checkbox } from '../common/FormControls'
import { Input } from '../common/Input'
import { ROUTES } from '../../constants/routes'
import { useAuth } from '../../hooks/useAuth'

export function RegisterForm() { const { register } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '', terms: false }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  const update = (key: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }))
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); if (form.name.trim().length < 2) return setError('Full name must contain at least 2 characters.'); if (!/^\S+@\S+\.\S+$/.test(form.email)) return setError('Please enter a valid email address.'); if (form.password.length < 8) return setError('Password must contain at least 8 characters.'); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); if (!form.terms) return setError('You must accept the terms to continue.'); setLoading(true); try { await register(form); navigate(ROUTES.userDashboard, { replace: true }) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to create your account.') } finally { setLoading(false) } }
  return <form className="az-auth-form" onSubmit={submit} noValidate><Input label="Full Name" autoComplete="name" value={form.name} onChange={(e) => update('name', e.target.value)} /><Input label="Email" type="email" autoComplete="email" value={form.email} onChange={(e) => update('email', e.target.value)} /><Input label="Password" type="password" autoComplete="new-password" value={form.password} onChange={(e) => update('password', e.target.value)} /><Input label="Confirm Password" type="password" autoComplete="new-password" value={form.confirmPassword} onChange={(e) => update('confirmPassword', e.target.value)} /><Checkbox label="I accept the Terms of Use and Privacy Policy" checked={form.terms} onChange={(e) => update('terms', e.target.checked)} />{error && <p className="az-auth-error" role="alert">{error}</p>}<Button type="submit" fullWidth loading={loading}>{loading ? 'Creating account...' : 'Create Account'}</Button><p className="az-auth__footer">Already have an account? <Link to={ROUTES.login}>Sign In</Link></p></form> }
